### ISSUE TITLE
Support Kustomizations and Deployable Artifacts

### ISSUE THREAD

**Issue by bc185174** [spegel-org/spegel#330]
### Describe the problem to be solved

Support for deploying Spegel using Kustomizations so it can natively be deployed to a cluster using kubectl `kubectl apply -k https://github.com/XenitAB/spegel/archive/refs/tags/spegel-v0.0.17.yaml`. This would also benefit those using automation to download the deployment manifests and patch them using Kustomize as the end-users sees fit. 

### Proposed solution to the problem

Add Kustomizations in `config/spegel` directory and produce a single artifact that can be applied using kubectl `kubectl apply -k https://github.com/XenitAB/spegel/archive/refs/tags/spegel-v0.0.17.yaml`.

**Comment by phillebaba** [comment]
It would be great if we could support generating Kustomizaton from the Helm chart to reduce the work required. It has been a while since I have looked at how others solve this. Do you know of any tool which would be able to do something similar?

**Comment by bc185174** [comment]
> It would be great if we could support generating Kustomizaton from the Helm chart to reduce the work required. It has been a while since I have looked at how others solve this. Do you know of any tool which would be able to do something similar?

Yeah, you can use `helm template` on the default `values.yaml` and add a basic `Kustomization` to deploy the resources. A fair few go projects like https://github.com/kubevirt/kubevirt use Bazel to automate a lot of building/testing processes - you can import the `helm` binary and add a target to render (template) the helm chart to a file.

**Comment by tomberget** [comment]
Just chiming in for a possible solution to this. Why not use the kustomize helmChart feature?

Then you should be able to add items like this:

In the `/base/kustomization.yaml`:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: spegel
    releaseName: spegel
    version: 0.0.x (or 0.0.18)
    repo: oci://ghcr.io/xenitab/helm-charts/spegel
    namespace: spegel
    valuesFile: ./values.yaml
    includeCRDs: true

patches:
  - path: something.yaml
    target:
      version: v1
      group: apps
      kind: DaemonSet
      name: <whatever>
```

At least if you are using kustomize above version 5.2.1 (or something like that), OCI registries are supported in `helmChart`, and _should_ be possible by using:

```bash
kustomize build path/to/overlay --enable-helm
```
