### ISSUE TITLE
GKE Support

### ISSUE THREAD

**Issue by phillebaba** [spegel-org/spegel#38]
Currently it does not seem like there is an easy way to support GKE. When creating a cluster the Containerd config looks like the following.

```toml
version = 2
required_plugins = ["io.containerd.grpc.v1.cri"]
# Kubernetes doesn't use containerd restart manager.
disabled_plugins = ["io.containerd.internal.v1.restart"]
oom_score = -999

[debug]
  level = "info"

[grpc]
  gid = 412

[plugins."io.containerd.grpc.v1.cri"]
  stream_server_address = "127.0.0.1"
  max_container_log_line_size = 262144
  sandbox_image = "gke.gcr.io/pause:3.6@sha256:10008c36b4611b44db1229451675d5d7d86c7ddf4ef00f883d806a01547203f6"
[plugins."io.containerd.grpc.v1.cri".cni]
  bin_dir = "/home/kubernetes/bin"
  conf_dir = "/etc/cni/net.d"
  conf_template = "/home/containerd/cni.template"
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
  endpoint = ["https://mirror.gcr.io","https://registry-1.docker.io"]
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  SystemdCgroup = false
[plugins."io.containerd.grpc.v1.cri".containerd]
  default_runtime_name = "runc"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
```

The issue here is that it does not configure the prerequisite `config_path`. Without it Containerd will not look for any mirror configuration. 

One interesting point to notice is that GKE is using the old mirror syntax to configure a specific mirror for Docker Hub. This is most likely a part of a feature they offer as they will cache Docker Hub images to avoid rate limiting. It would be better if they used the newer mirror configuration method. As even if Spegel would override this, it could be configured to when run in a GKE cluster keep the last mirror fallback for Docker Hub.

**Comment by phillebaba** [comment]
I have checked GKE again and this is still an issue due to the config path not being set.

**Comment by irLinja** [comment]
I tested this today on GKE `v1.29.1-gke.1589000` the configuration path is not set.

**Comment by phillebaba** [comment]
I do not see a way forward here other than waiting for Containerd to remove support for the old mirror configuration method which would in turn force Google to update their Containerd configuration. Unless someone has a good contact with the GKE team to get them to do it earlier.

**Comment by stenh0use** [comment]
I spoke with the GKE team a while back about this, they didn't offer much except to modify the config via a privileged daemonset or wait until containerd v2 is released. I don't know how helpful this is as it sounds like you don't want to change the config? Anyway, It should work in theory, but I haven't tested it.

1. Remove the current mirror definition
```
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
  endpoint = ["https://mirror.gcr.io","https://registry-1.docker.io"]
```
3. Configure the registry with `/etc/containerd/hosts.d` instead of `/etc/containerd/certs.d`
```
[plugins."io.containerd.grpc.v1.cri".registry]
  config_path = "/etc/containerd/hosts.d" 
```
4. Set discard_unpacked_layers to false
```
[plugins."io.containerd.grpc.v1.cri".containerd]
   discard_unpacked_layers = false
```
6. Add the fallback mirrors under `/etc/containerd/hosts.d/docker.io/hosts.toml`
```
server = "https://docker.io"

[host."https://mirror.gcr.io"]
  capabilities = ["pull", "resolve"]

[host."https://registry-1.docker.io"]
  capabilities = ["pull", "resolve"]
```
7. Restart containerd systemd service
8. Configure spegel with `--containerd-registry-config-path=/etc/containerd/hosts.d`

**Comment by mKeRix** [comment]
We have managed to get this working, but it requires some workarounds due to GKE limitations. Our setup currently still runs containerd v1 with the configuration as set by node auto-provisioning. This will also only work for standard clusters, not autopilot ones.

In our setup, we run a separate daemonset for configuring containerd. It is important that you use something like [nidhogg](https://github.com/pelotech/nidhogg) to set a startup taint for this daemonset. Containerd restarts can mess with init containers, which can be an issue if you have containers that are not idempotent (e.g. istio-init). If you use node auto-provisioning like we do, note that you'll have to write a mutating webhook that adds this taint to the nodes when they are created, as there is no other native way to add startup taints with NAP. We have built a simple Kyverno policy for this. Make sure to allow to set the failure mode to `Ignore` here, otherwise you might deadlock your cluster. 

We store a script in a secret, as this also contains credentials for us, but you could also just put this into a configmap if you do not need this part. Start by creating a secret (or similar) with content like this, potentially extended by whatever other configuration you want to have (in our case this is templated):

```shell
#!/usr/bin/env sh
set -euo pipefail
ROOT_MOUNT_DIR="${ROOT_MOUNT_DIR:-/host}"

dasel put -f ${ROOT_MOUNT_DIR}/etc/containerd/config.toml -r toml -w toml -v '/etc/containerd/certs.d' 'plugins.property(io.containerd.grpc.v1.cri).registry.config_path'
dasel put -f ${ROOT_MOUNT_DIR}/etc/containerd/config.toml -r toml -w toml -v 'false' -t 'bool' 'plugins.property(io.containerd.grpc.v1.cri).containerd.discard_unpacked_layers'
# may fail if this has already been deleted, hence we ignore failures
dasel delete -f ${ROOT_MOUNT_DIR}/etc/containerd/config.toml -r toml -w toml 'plugins.property(io.containerd.grpc.v1.cri).registry.mirrors' || true

mkdir -p ${ROOT_MOUNT_DIR}/etc/containerd/certs.d/ghcr.io
cat <<-EOF > ${ROOT_MOUNT_DIR}/etc/containerd/certs.d/ghcr.io/hosts.toml
server = "https://ghcr.io"
[host."http://${NODE_IP}:30020"]
capabilities = ["pull", "resolve"]
[host."http://${NODE_IP}:30021"]
capabilities = ["pull", "resolve"]
EOF

chown -R root ${ROOT_MOUNT_DIR}/etc/containerd/certs.d/
chmod -R 0644 ${ROOT_MOUNT_DIR}/etc/containerd/certs.d/

chroot "${ROOT_MOUNT_DIR}" /bin/systemctl restart containerd
echo "credentials injected"
```

Then you can create a daemonset that uses this script to configure containerd on node startup:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cos-containerd-registry-credentials
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: cos-containerd-registry-credentials
      app.kubernetes.io/name: registry-credentials
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: cos-containerd-registry-credentials
        app.kubernetes.io/name: registry-credentials
    spec:
      containers:
      - image: registry.k8s.io/pause:3.10
        name: pause
      hostPID: true
      initContainers:
      - command:
        - /scripts/cos-containerd.sh
        env:
        - name: ROOT_MOUNT_DIR
          value: /host
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: ghcr.io/tomwright/dasel:v2.8.1-alpine
        name: credential-init
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: root
        - mountPath: /scripts
          name: entrypoint
      nodeSelector:
        cloud.google.com/gke-container-runtime: containerd
        cloud.google.com/gke-os-distribution: cos
        kubernetes.io/os: linux
      tolerations:
      - effect: NoSchedule
        key: your-startup-taint
        operator: Exists
      - effect: NoSchedule
        key: cloud.google.com/compute-class
        operator: Exists
      volumes:
      - hostPath:
          path: /
        name: root
      - name: entrypoint
        secret:
          defaultMode: 484
          optional: false
          secretName: registry-credentials-script
```

For your spegel installation you can then add `--set spegel.containerdMirrorAdd=false` because that part was already taken care of. When using this approach, the daemonset becomes critical to scaling your cluster - I would heavily recommend to not rely on external registries directly, but instead have a cache that you can trust.
