### ISSUE TITLE
Default to docker.io

### ISSUE THREAD

**Issue by mrclrchtr** [spegel-org/spegel#423]
### Describe the problem to be solved

Hi, I would like to use spegel as a pull through cache in my pipeline. There images are often specified as follows:
```
image: flyway/flyway:10.11.0
```
Spegel then says the following error message:
```
"path":"/v2/flyway/flyway/manifests/10.11.0","status":404,"method":"GET","latency":0.000058161,"ip":"10.0.19.75","error":"registry parameter needs to be set for tag references"
```

### Proposed solution to the problem

My understanding is that there is always implicitly "docker.io" as registry in front of this notation or? Would it be possible to set this default instead of throwing the error message? Or at least offer the option to set a default?

**Comment by phillebaba** [comment]
I will have to dig deeper into Containerd image pulling logic and Kubernetes sends image references through the CRI API.

While Docker does implicitly assume that the registry is docker.io that is not the case for Containerd. When pulling with ctr for example it requires you to give a full image reference including the registry.

The interesting thing that is happening here is that Containerd is picking up the registry in the mirror configuration, but is not adding the original registry in the mirrored HTTP request. While defaulting would solve this specific problem, I think that we need to understand the core issue of why this is occurring.

**Comment by mrclrchtr** [comment]
Thank you very much for the very quick response!

Ah ok, you're right.

Which might also be interesting (maybe that's what you mean by "Containerd is picking up the registry in the mirror configuration"): The download still works, even though I specified Spegel as the mirror only. Unfortunately, I'm not sure whether Docker simply sends a request to docker.io anyway if Spegel responds with a 404? In any case, the images are available at the end.

**Comment by phillebaba** [comment]
I just ran the e2e tests without the registry specified and it worked without any issues so we need to dig a bit deeper into this.

To make sure that we are on the same page. Am I right to assume that you are running Spegel in Kubernetes and specifying the image references in a Pod spec? Or are you using Spegel in some other fashion. The reason I ask is that there is a difference between how Containerd will pull an image and how Docker would, which is critical for the functionality of Spegel.

Could you just quickly describe your environment so that I can better understand where the error originates from.

**Comment by mrclrchtr** [comment]
Yes sure:
- Talos Kubernetes
- Spegel per Helm v0.0.20

Values
```yaml
spegel:
  containerdRegistryConfigPath: /etc/cri/conf.d/hosts
serviceMonitor:
  enabled: true
```

All Pods are automatically pulling their images successfully. So it's basically working as expected.

I want to use it in gha-runner-scale-set:
```yaml
      - image: docker:26.0.0-dind
        name: dind
        securityContext:
          privileged: true
        env:
          - name: DOCKER_GROUP_GID
            value: "123"
        args:
          - dockerd
          - --host=unix:///var/run/docker.sock
          - --group=$(DOCKER_GROUP_GID)
          - --registry-mirror=http://spegel-registry.spegel.svc.cluster.8log.de.local:5000
        volumeMounts:
          - mountPath: /home/runner/_work
            name: work
          - mountPath: /var/run
            name: dind-sock
          - mountPath: /home/runner/externals
            name: dind-externals
```

`--registry-mirror=http://spegel-registry.spegel.svc.cluster.8log.de.local:5000` is the relevant part to connect the dind to spegel. Thats also working as expected, but with the error messages described.

Do you need further information?
