### ISSUE TITLE
estargz-snapshotter support

### ISSUE THREAD

**Issue by phillebaba** [spegel-org/spegel#510]
A question was raised by @ChrisBr in #176 if Spegel would support estargz-snapshotter. As it functions differently from SOCI it will require its own analysis to determine if it is possible to use with Spegel.

**Comment by phillebaba** [comment]
Looks like the docs for mirror configuration are not up to date. However it seems like the snapshotter supports the newer CRI hosts mirror configuration. We can check the k3s PR for an example for how that would work.

https://github.com/containerd/stargz-snapshotter/issues/1647

At minimum we need to document this here as it is not documentated in stargz-snapshotter. I would like to add a test for this to verify that this is also working. The open question is whether we should add this check to verify to make sure that this configuration is set.

**Comment by phillebaba** [comment]
Still need to test this but it seems like all that needs to be changed, assuming the snapshotter is properly configured, is to change the registry config slightly.

```toml
[plugins."io.containerd.grpc.v1.cri".registry]
  config_path = "/etc/containerd/certs.d"
```

Compared to.

```toml
[plugins."io.containerd.snapshotter.v1.stargz".registry]
  config_path = "/etc/containerd/certs.d"
```
