### ISSUE TITLE
Remove predefined node taint after spegel pod finished initializing on the node

### ISSUE THREAD

**Issue by shandr** [spegel-org/spegel#587]
### Describe the problem to be solved

On EKS, with Karpenter for nodes provisioning, in 99%, the workload pod starts before the spegel daemonset configures the node. This makes spegel useless in dynamic EKS + Karpenter environments. The suggested in the FAQ solution **nidhogg** is very unstable and not working as expected or not working at all. Additionally, with Karpenter, adding a taint that Karpenter is unaware of on the node can lead to a situation when Karpenter will create new nodes, because the pod doesn't have the required toleration.

### Proposed solution to the problem

Use the "cilium" [approach](https://docs.cilium.io/en/stable/installation/taints/). With Karpenter (or some other methods) add [startupTaints](https://karpenter.sh/docs/concepts/nodepools/#cilium-startup-taint) with some predefined name. When spegel initialized, it should remove the taint from the node.

**Comment by phillebaba** [comment]
I wish this was a solution provided in Kubernetes. There have been a couple of solutions proposed and none of them have been accepted. I wish that every project did not need to implement their own solution to fix this challenge.

I am for creating a solution that would work for both Karpenter users and Cluster Autoscaler users short term. Long term we should consider a KEP to solve this problem in Kubernetes.

**Comment by shandr** [comment]
With Cluster Autoscaler it's also possible to add some custom taint to Managed Nodegroups that spegel can remove after initialization. So it should work for both.

**Comment by phillebaba** [comment]
Removing node taints would require introducing Kubernetes API dependencies and RBAC permissions to Spegel, which goes against its design goals of staying lightweight and stateless.

For those looking for this kind of automation, the feature has been added to the Prisma controller, Spegel’s enterprise offering.

**Comment by zoispag** [comment]
I will revive this issue, pointing to https://node-readiness-controller.sigs.k8s.io/ (alpha) which I believes will solve this very problem, without relying on nidhogg.

**Comment by phillebaba** [comment]
@zoispag I think this is a great idea as the controller will hopefully become a native feature eventually. The original Nidhogg repo is not being maintained anymore and NRC seems like it may be around.

If you have success getting something working it would be great to add it to the docs and replace Nidhogg as the recommended solution.  Going forward it could also be a resource which could be added to the Helm chart as an opt in?

**Comment by zoispag** [comment]
@phillebaba once I'm back from my vacation, I will experiment and document a working solution. Can we reopen this issue?

**Comment by zoispag** [comment]
Following up on my earlier comment about the [Node Readiness Controller](https://node-readiness-controller.sigs.k8s.io/) — after experimenting with it, we decided it was not the right fit. It's still in alpha, adds another controller to manage, and the `NodeReadinessPolicy` CRD felt heavyweight for what is essentially "wait for a DaemonSet pod to be ready, then untaint the node."

Instead, we implemented exactly what @shandr originally proposed: the **Cilium-style approach** using Karpenter `startupTaints` and a lightweight sidecar DaemonSet that removes the taint once Spegel is ready. Here's how it works in production:

### 1. Karpenter NodePool: add a `startupTaint`

```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: my-nodepool
spec:
  template:
    spec:
      startupTaints:
      - key: spegel.io/not-ready
        effect: NoSchedule
```

Karpenter applies this taint to every new node at launch. Regular workloads don't tolerate it, so they stay `Pending` until the taint is removed. Karpenter is aware of startupTaints, so it won't spin up extra nodes due to untolerated taints — it knows they're transient.

### 2. Taint-remover DaemonSet

A simple DaemonSet that:
- Tolerates the `spegel.io/not-ready` taint (so it schedules on new nodes immediately)
- Uses `hostNetwork: true` to reach Spegel's registry at `127.0.0.1:<port>`
- Polls Spegel's `/readyz` endpoint in a loop
- Once Spegel reports ready, removes the taint via `kubectl taint node`

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spegel-taint-remover
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    spec:
      serviceAccountName: spegel-taint-remover
      priorityClassName: system-cluster-critical
      tolerations:
      - key: spegel.io/not-ready
        effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      nodeSelector:
        kubernetes.io/os: linux
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: taint-remover
        image: docker.io/alpine/k8s:1.35.3
        command:
        - /bin/sh
        - -c
        - |
          until wget -qO- http://127.0.0.1:5000/readyz > /dev/null 2>&1; do
            sleep 2
          done
          attempt=1
          while true; do
            output=$(kubectl taint node "${NODE_NAME}" spegel.io/not-ready:NoSchedule- 2>&1) && {
              echo "node ${NODE_NAME} is ready: taint 'spegel.io/not-ready:NoSchedule' removed"
              break
            }
            if echo "${output}" | grep -q "not found"; then
              echo "taint 'spegel.io/not-ready:NoSchedule' not present on node ${NODE_NAME}, nothing to remove"
              break
            fi
            echo "taint removal failed (attempt ${attempt}): ${output} — retrying in 5s..." >&2
            attempt=$((attempt + 1))
            sleep 5
          done
          trap 'exit 0' TERM INT
          tail -f /dev/null &
          wait $!
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            memory: 32Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65532
```

### 3. RBAC

The DaemonSet's ServiceAccount needs a ClusterRole with `get` and `patch` on `nodes`:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spegel-taint-remover
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch"]
```

### How it plays out on a new node

1. Karpenter provisions a node with taint `spegel.io/not-ready:NoSchedule`
2. Only system-critical pods + the taint-remover DaemonSet schedule (they tolerate the taint)
3. Spegel DaemonSet starts and begins populating its P2P registry
4. Taint-remover polls `127.0.0.1:5000/readyz` every 2 seconds
5. Once Spegel responds healthy, taint-remover runs `kubectl taint node ... spegel.io/not-ready:NoSchedule-`
6. Taint is removed → regular workloads start scheduling → they pull images via Spegel's local mirror

This works reliably for both Karpenter and Cluster Autoscaler (for CA, add the taint to the ManagedNodeGroup/ASG launch template instead of `startupTaints`).

### Limitations and what we did next

This approach **does** work — we ran it in production on EKS with Karpenter for several months. The main downside is that it adds a few seconds to node readiness (the readyz polling loop + taint removal), and you're carrying an extra DaemonSet.

For our specific use case (large ~4GB Matlab images on ephemeral job nodes), we eventually moved to **EBS snapshot-based image caching**: the containerd data store is pre-populated on a snapshot and mounted at boot via Karpenter's `EC2NodeClass` `blockDeviceMappings`. This eliminates the need for Spegel entirely on those nodes since images are already on disk. But for general-purpose nodes where you want P2P mirroring, the startupTaint + taint-remover approach above is a solid, simple solution.

Happy to answer questions if anyone wants more detail on either approach.
