### ISSUE TITLE
#373 appears to break spegel chart functionality

### ISSUE THREAD

**Issue by billimek** [spegel-org/spegel#813]
### Spegel version

0.1.1

### Kubernetes distribution

K3S

### Kubernetes version

v1.31.7

### CNI

flannel

### Describe the bug

[#373](https://github.com/spegel-org/spegel/pull/373) appears to render spegel chart not usable, at least in k3s:

After upgrading from v0.30.0 to 0.1.1 k3s and containerd no longer find images hosted in the removed public upstream registries.

See [these details](https://github.com/billimek/k8s-gitops/issues/4349) for the exact error messages and eventual remedy of reverting spegel chart to the earlier v0.30.0 version

**Comment by billimek** [comment]
Forgot to reference the spegel helm chart values [used](https://github.com/billimek/k8s-gitops/blob/master/kube-system/spegel/spegel.yaml#L26C1-L39C20):

```yaml
    spegel:
      containerdSock: /run/k3s/containerd/containerd.sock
      containerdRegistryConfigPath: /var/lib/rancher/k3s/agent/etc/containerd/certs.d
      containerdContentPath: /var/lib/rancher/k3s/agent/containerd/io.containerd.content.v1.content
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 1Gi
```
