### ISSUE TITLE
`path: /metrics, status: 404` on a new install

### ISSUE THREAD

**Issue by JunaidChaudry** [spegel-org/spegel#833]
I just installed spegel, and see the following error constantly popping up in all the registry pods. Can anyone explain what this means, and why that is happening? 

**Error:**
```
{"time":"2025-04-17T18:49:34.491685681Z","level":"ERROR","source":{"function":"github.com/spegel-org/spegel/pkg/registry.(*Registry).handle.func1","file":"/build/pkg/registry/registry.go","line":144},"msg":"","path":"/metrics","status":404,"method":"GET","latency":"7.64µs","ip":"x.x.x.x","handler":""}
```

I am using default values, with only the following change:
```
fullnameOverride: spegel-test
```

**Comment by fanbondi** [comment]
Have you enabled monitoring?

**Comment by JunaidChaudry** [comment]
`serviceMonitor.enabled` is `false`. So I would assume that disables monitoring? 

And I do have prometheus running on the cluster, but in its own namespace `prometheus`

![Image](https://github.com/user-attachments/assets/5eaebd61-1b9f-4c2e-bd21-30603e32ef25)

**Comment by JunaidChaudry** [comment]
in other words, I did not enable monitoring, and even if it is enabled, then not sure why it is not able to find prometheus

**Comment by phillebaba** [comment]
It looks like you are sending metrics poll requests to the registry server on port 5000 rather than to the metrics server on port 9090. How are you configuring Prometheus to scrape the metrics endpoint. Are you using the service monitor in the Helm chart?

**Comment by JunaidChaudry** [comment]
> It looks like you are sending metrics poll requests to the registry server on port 5000 

Is that a default by any chance that I don't see in the `values`, because I definitely did not specify that myself in my values? 

> Are you using the service monitor in the Helm chart?

I actually tried it with both options `serviceMonitor.enabled: true` as well as `false`, but ended up with the same result in both. 

Here's my values.yaml for reference: 


```yaml
fullnameOverride: spegel-test

# affinity to not select managed worker groups 
  # --- managed groups don't have NodeConfig to disable discard_unpacked_layers
affinity: 
  nodeAffinity: 
    requiredDuringSchedulingIgnoredDuringExecution: 
      nodeSelectorTerms: 
        - matchExpressions: 
          - key: worker-group
            operator: DoesNotExist

priorityClassName: system-node-critical

serviceMonitor: 
  enabled: false

spegel:
  logLevel: "INFO"
  mirroredRegistries: []
  additionalMirrorTargets: []
  mirrorResolveRetries: 3
  mirrorResolveTimeout: "20ms"
  # -- When true enables debug web page.
  debugWebEnabled: false

```
