### ISSUE TITLE
serviceMonitor annotations for Helm

### ISSUE THREAD

**Issue by csc-piscopo** [spegel-org/spegel#893]
### Describe the problem to be solved

Any chance of adding annotations to the serviceMonitor template? We are using k8s-monitoring and I am wanting to add the following annotations for autodiscovery:

```yaml
    k8s.grafana.com/job: k8s-monitoring/spegel
    k8s.grafana.com/metrics.portName: metrics
    k8s.grafana.com/metrics.portNumber: '9090'
    k8s.grafana.com/scrape: 'true'
```

https://github.com/spegel-org/spegel/blob/f1cf2530e505b19a14e2190df77ad1faa6fa7f56/charts/spegel/templates/servicemonitor.yaml

### Proposed solution to the problem

Adding a section for annotations within the serviceMonitor template should do the trick:

```yaml
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spegel.fullname" . }}
  namespace: {{ include "spegel.namespace" . }}
  annotations:
    {{- include "spegel.annotations" . | nindent 4 }}
    {{- if .Values.serviceMonitor.annotations -}}
    {{ toYaml .Values.serviceMonitor.annotations | nindent 4}}
    {{- end }}
```
